// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGewsGiW0SvoEJuxc64RR7lutYSSatOKo',
    appId: '1:217158479906:web:ebe70bf60bbad7e42a5a7b',
    messagingSenderId: '217158479906',
    projectId: 'aristeia-d7d47',
    authDomain: 'aristeia-d7d47.firebaseapp.com',
    storageBucket: 'aristeia-d7d47.appspot.com',
    measurementId: 'G-X77D4R7YLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgClWzP8VQKim6HDEcYX8GxxdkDOmbms',
    appId: '1:217158479906:android:b7527087450354fa2a5a7b',
    messagingSenderId: '217158479906',
    projectId: 'aristeia-d7d47',
    storageBucket: 'aristeia-d7d47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVE-MwRvSnxj870zLz1WcuwkjUmEK3ZM',
    appId: '1:217158479906:ios:f372ebceb63455d92a5a7b',
    messagingSenderId: '217158479906',
    projectId: 'aristeia-d7d47',
    storageBucket: 'aristeia-d7d47.appspot.com',
    iosClientId: '217158479906-rjmkmgoie4qjkbjt72rql6dp9373aisq.apps.googleusercontent.com',
    iosBundleId: 'com.example.aristeiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVE-MwRvSnxj870zLz1WcuwkjUmEK3ZM',
    appId: '1:217158479906:ios:f372ebceb63455d92a5a7b',
    messagingSenderId: '217158479906',
    projectId: 'aristeia-d7d47',
    storageBucket: 'aristeia-d7d47.appspot.com',
    iosClientId: '217158479906-rjmkmgoie4qjkbjt72rql6dp9373aisq.apps.googleusercontent.com',
    iosBundleId: 'com.example.aristeiaApp',
  );
}
